from typing import TypedDict


class EmojiCategory(TypedDict):
    icon: str
    name: str
    emojis: list[tuple[str, str, str]]


EMOJI_CATEGORIES: list[EmojiCategory] = [
    {
        "icon": "😀",
        "name": "Smileys",
        "emojis": [
            ("😀", "grinning", "grin happy face"),
            ("😃", "grinning_big", "big smile happy joy"),
            ("😄", "grinning_eyes", "smile laughing happy eyes"),
            ("😁", "beaming", "beaming grin happy teeth"),
            ("😅", "sweat", "grin sweat nervous"),
            ("😂", "joy", "laugh crying tears funny"),
            ("🤣", "rolling", "rolling floor laughing hilarious"),
            ("😊", "blush", "smile blush happy shy"),
            ("😇", "innocent", "angel halo smile sweet"),
            ("🙂", "slight_smile", "slight smile subtle"),
            ("😉", "wink", "wink flirt playful"),
            ("😌", "relieved", "relieved sigh content"),
            ("😍", "heart_eyes", "love heart eyes adore"),
            ("🥰", "three_hearts", "love smile hearts"),
            ("😘", "kiss", "kiss heart love blow"),
            ("😗", "kissing", "kissing face"),
            ("😋", "yum", "yum delicious tongue"),
            ("😛", "tongue", "tongue out playful"),
            ("😜", "wink_tongue", "wink tongue joking"),
            ("😝", "squint_tongue", "squint tongue silly"),
            ("🤑", "money", "money tongue dollar rich"),
            ("🤗", "hugs", "hug open hands embrace"),
            ("🤭", "hand_over_mouth", "oops secret mouth hand"),
            ("🫣", "peeking", "peeking shy hidden"),
            ("🤐", "zipper", "zipper mouth silent secret"),
            ("🤨", "raised_eyebrow", "skeptical eyebrow doubt"),
            ("😐", "neutral", "neutral face meh"),
            ("😑", "expressionless", "expressionless blank"),
            ("😶", "no_mouth", "speechless quiet no mouth"),
            ("😏", "smirk", "smirk smug confident"),
            ("😒", "unamused", "unamused annoyed roll eyes"),
            ("🙄", "face_roll", "eye roll annoyed"),
            ("😬", "grimace", "grimace awkward cringe"),
            ("🤥", "lying", "lying nose pinocchio"),
            ("😔", "pensive", "pensive sad disappointed"),
            ("😕", "confused", "confused puzzled"),
            ("🙃", "upside_down", "upside down silly sarcastic"),
            ("😢", "cry", "cry tear sad"),
            ("😭", "sob", "crying loudly bawling"),
            ("😤", "fume", "frustrated steam angry"),
            ("😠", "angry", "angry mad furious"),
            ("😡", "rage", "red angry furious rage"),
            ("🤬", "cursing", "cursing swear mad"),
            ("😈", "devil_smile", "devil smile mischievous"),
            ("👿", "devil_angry", "angry devil evil"),
            ("💀", "skull", "skull death dead"),
            ("☠️", "skull_cross", "skull crossbones danger"),
            ("💩", "poop", "poop feces shit"),
            ("🤡", "clown", "clown circus funny"),
            ("👹", "ogre", "ogre monster red"),
            ("👺", "goblin", "goblin nose long"),
            ("👻", "ghost", "ghost boo spooky"),
            ("👽", "alien", "alien ufo extraterrestrial"),
            ("🤖", "robot", "robot ai machine"),
            ("😺", "cat_grin", "grinning cat smile"),
            ("😸", "cat_smile", "smile cat happy"),
            ("😹", "cat_joy", "cat tears laughing"),
            ("😻", "cat_hearts", "cat love heart eyes"),
            ("😼", "cat_wry", "cat smirk wry"),
            ("😽", "cat_kiss", "kissing cat"),
            ("🙀", "cat_weary", "cat weary surprised"),
            ("😿", "cat_cry", "crying cat sad"),
            ("😾", "cat_pout", "pouting cat"),
        ],
    },
    {
        "icon": "👋",
        "name": "Gestures",
        "emojis": [
            ("👋", "wave", "wave hello hand goodbye"),
            ("🤚", "raised_back", "raised back hand"),
            ("🖐️", "spread", "hand spread five"),
            ("✋", "raised", "raised hand stop high five"),
            ("🖖", "vulcan", "vulcan salute star trek"),
            ("👌", "ok", "ok hand perfect"),
            ("🤌", "pinched", "pinched fingers italian"),
            ("🤏", "pinching", "pinching small tiny"),
            ("✌️", "victory", "victory peace v hand"),
            ("🤞", "cross", "crossed fingers luck"),
            ("🫰", "index_thumb", "hand with index and thumb"),
            ("🤟", "love_gesture", "love you gesture ilu"),
            ("🤘", "horns", "rock horns sign of horns"),
            ("🤙", "call_me", "call me hand phone"),
            ("👈", "left", "point left backhand"),
            ("👉", "right", "point right backhand"),
            ("👆", "up", "point up backhand"),
            ("🖕", "middle", "middle finger rude"),
            ("👇", "down", "point down backhand"),
            ("☝️", "index_up", "index pointing up"),
            ("👍", "thumbs_up", "thumbs up like good"),
            ("👎", "thumbs_down", "thumbs down dislike"),
            ("✊", "fist", "raised fist power"),
            ("👊", "oncoming_fist", "fist bump punch"),
            ("🤛", "left_fist", "left facing fist"),
            ("🤜", "right_fist", "right facing fist"),
            ("👏", "clap", "clap applaud bravo"),
            ("🙌", "raised_hands", "raised hands celebrate hooray"),
            ("👐", "open_hands", "open hands hug"),
            ("🤲", "palms_up", "palms up together pray"),
            ("🤝", "handshake", "handshake agreement deal"),
            ("🙏", "pray", "pray please thank you"),
            ("✍️", "writing", "writing hand"),
            ("💅", "nail_polish", "nail polish care free"),
            ("🤳", "selfie", "selfie phone camera"),
            ("💪", "bicep", "bicep flex strong muscle"),
            ("🦶", "foot", "foot step"),
            ("👂", "ear", "ear hear listen"),
            ("👃", "nose", "nose smell sniff"),
            ("🧠", "brain", "brain mind intelligence"),
            ("🫀", "heart_organ", "anatomical heart"),
            ("👁️", "eye", "eye see vision"),
            ("👀", "eyes", "eyes look watching"),
            ("👅", "tongue", "tongue taste"),
            ("👄", "lips", "lips mouth kiss"),
        ],
    },
    {
        "icon": "🐻",
        "name": "Animals",
        "emojis": [
            ("🐶", "dog", "dog puppy pet"),
            ("🐱", "cat", "cat kitten pet meow"),
            ("🐭", "mouse", "mouse rat small"),
            ("🐹", "hamster", "hamster pet rodent"),
            ("🐰", "rabbit", "rabbit bunny hare"),
            ("🦊", "fox", "fox sly cunning"),
            ("🐻", "bear", "bear brown grizzly"),
            ("🐼", "panda", "panda bamboo china"),
            ("🐨", "koala", "koala australia sleepy"),
            ("🐯", "tiger", "tiger stripes big cat"),
            ("🦁", "lion", "lion king roar"),
            ("🐮", "cow", "cow milk moo"),
            ("🐷", "pig", "pig piggy oink"),
            ("🐸", "frog", "frog croak toad"),
            ("🐵", "monkey", "monkey face primate"),
            ("🐔", "chicken", "chicken hen poultry"),
            ("🐧", "penguin", "penguin antarctica bird"),
            ("🐦", "bird", "bird tweet fly"),
            ("🐤", "chick", "baby chick chicken"),
            ("🦆", "duck", "duck quack"),
            ("🦅", "eagle", "eagle bird prey america"),
            ("🦉", "owl", "owl night wise"),
            ("🦇", "bat", "bat vampire nocturnal"),
            ("🐺", "wolf", "wolf howl pack"),
            ("🐗", "boar", "boar wild pig"),
            ("🐴", "horse", "horse face equine"),
            ("🦄", "unicorn", "unicorn fantasy mythical"),
            ("🐝", "bee", "bee honey insect buzz"),
            ("🐛", "bug", "bug caterpillar insect"),
            ("🦋", "butterfly", "butterfly wings beautiful"),
            ("🐌", "snail", "snail slow shell"),
            ("🐞", "ladybug", "ladybug beetle bug"),
            ("🐜", "ant", "ant insect worker"),
            ("🦟", "mosquito", "mosquito bite malaria"),
            ("🦗", "cricket", "cricket insect chirp"),
            ("🪰", "fly", "fly insect buzz"),
            ("🪳", "cockroach", "cockroach roach pest"),
            ("🕷️", "spider", "spider web arachnid"),
            ("🦂", "scorpion", "scorpion sting desert"),
            ("🐢", "turtle", "turtle tortoise slow"),
            ("🐍", "snake", "snake serpent reptile"),
            ("🦎", "lizard", "lizard reptile gecko"),
            ("🦖", "t_rex", "t rex dinosaur trex"),
            ("🦕", "sauropod", "sauropod dinosaur brontosaurus"),
            ("🐙", "octopus", "octopus tentacles ocean"),
            ("🦑", "squid", "squid calamari ocean"),
            ("🦐", "shrimp", "shrimp prawn seafood"),
            ("🐬", "dolphin", "dolphin ocean friendly"),
            ("🐳", "whale", "whale ocean spout"),
            ("🐋", "orca", "orca whale killer"),
            ("🐟", "fish", "fish swim ocean"),
            ("🦈", "shark", "shark jaws fish"),
            ("🐊", "crocodile", "crocodile alligator reptile"),
            ("🦜", "parrot", "parrot talk pirate bird"),
            ("🦚", "peacock", "peacock feathers pride"),
            ("🌸", "cherry_blossom", "cherry blossom flower spring"),
            ("💐", "bouquet", "bouquet flowers gift"),
            ("🌹", "rose", "rose flower love romantic"),
            ("🌺", "hibiscus", "hibiscus flower tropical"),
            ("🌻", "sunflower", "sunflower plant bright"),
            ("🌷", "tulip", "tulip flower spring"),
            ("🌵", "cactus", "cactus desert plant"),
            ("🎄", "christmas", "christmas tree holiday"),
            ("🌲", "pine", "pine tree evergreen"),
            ("🌳", "deciduous", "deciduous tree leaf"),
            ("🍀", "clover", "clover four leaf luck"),
            ("🍁", "maple", "maple leaf canada"),
        ],
    },
    {
        "icon": "🍎",
        "name": "Food",
        "emojis": [
            ("🍇", "grapes", "grapes fruit wine"),
            ("🍈", "melon", "melon fruit"),
            ("🍉", "watermelon", "watermelon fruit summer"),
            ("🍊", "tangerine", "tangerine orange fruit"),
            ("🍋", "lemon", "lemon citrus sour"),
            ("🍌", "banana", "banana fruit potassium"),
            ("🍍", "pineapple", "pineapple fruit tropical"),
            ("🥭", "mango", "mango fruit tropical"),
            ("🍎", "apple", "apple fruit red"),
            ("🍏", "green_apple", "green apple fruit"),
            ("🍑", "peach", "peach fruit butt"),
            ("🍒", "cherries", "cherries fruit sweet"),
            ("🍓", "strawberry", "strawberry fruit berry"),
            ("🥝", "kiwi", "kiwi fruit"),
            ("🍅", "tomato", "tomato vegetable salad"),
            ("🥑", "avocado", "avocado guacamole toast"),
            ("🍆", "eggplant", "eggplant aubergine"),
            ("🥕", "carrot", "carrot vegetable orange"),
            ("🌽", "corn", "corn maize vegetable"),
            ("🥦", "broccoli", "broccoli vegetable green"),
            ("🧄", "garlic", "garlic seasoning vampire"),
            ("🧅", "onion", "onion vegetable tear"),
            ("🍄", "mushroom", "mushroom fungus"),
            ("🥜", "peanuts", "peanuts nuts snack"),
            ("🌰", "chestnut", "chestnut nut"),
            ("🍞", "bread", "bread loaf toast"),
            ("🧀", "cheese", "cheese wedge dairy"),
            ("🥚", "egg", "egg breakfast"),
            ("🍳", "cooking", "cooking frying pan egg"),
            ("🥓", "bacon", "bacon meat breakfast"),
            ("🥩", "steak", "steak meat beef cut"),
            ("🍔", "burger", "hamburger burger fast food"),
            ("🍟", "fries", "french fries fast food"),
            ("🍕", "pizza", "pizza italian slice"),
            ("🌭", "hotdog", "hot dog sausage"),
            ("🥪", "sandwich", "sandwich lunch"),
            ("🌮", "taco", "taco mexican tortilla"),
            ("🌯", "burrito", "burrito mexican wrap"),
            ("🥙", "pita", "stuffed pita gyro"),
            ("🧆", "falafel", "falafel middle eastern"),
            ("🥗", "salad", "salad green healthy"),
            ("🍿", "popcorn", "popcorn movie snack"),
            ("🧈", "butter", "butter dairy spread"),
            ("🥐", "croissant", "croissant french pastry"),
            ("🥨", "pretzel", "pretzel twisted snack"),
            ("🍦", "ice_cream", "ice cream dessert cold"),
            ("🍩", "doughnut", "doughnut donut dessert"),
            ("🍪", "cookie", "cookie dessert snack"),
            ("🎂", "birthday", "birthday cake celebration"),
            ("🍰", "cake", "cake dessert slice"),
            ("🧁", "cupcake", "cupcake dessert muffin"),
            ("🥧", "pie", "pie dessert pastry"),
            ("🍫", "chocolate", "chocolate candy sweet"),
            ("🍬", "candy", "candy sweet lollipop"),
            ("🍭", "lollipop", "lollipop candy sweet"),
            ("🍮", "custard", "custard pudding dessert"),
            ("🍯", "honey", "honey pot sweet"),
            ("☕", "coffee", "coffee tea hot beverage"),
            ("🍵", "tea", "tea green cup beverage"),
            ("🧃", "juice", "juice box drink"),
            ("🥛", "milk", "milk glass dairy"),
            ("🍺", "beer", "beer drink alcohol"),
            ("🍻", "clink_beer", "clinking beer glasses cheers"),
            ("🥂", "clink_glasses", "clinking glasses cheers toast"),
            ("🍷", "wine", "wine glass alcohol"),
            ("🥃", "tumbler", "whiskey tumbler shot"),
            ("🍸", "cocktail", "cocktail martini drink"),
            ("🍹", "tropical_drink", "tropical drink cocktail"),
            ("🧊", "ice", "ice cube cold"),
        ],
    },
    {
        "icon": "⚽",
        "name": "Activities",
        "emojis": [
            ("⚽", "soccer", "soccer football ball"),
            ("🏀", "basketball", "basketball hoop nba"),
            ("🏈", "football", "american football nfl"),
            ("⚾", "baseball", "baseball ball mlb"),
            ("🎾", "tennis", "tennis racket ball"),
            ("🏐", "volleyball", "volleyball ball"),
            ("🏉", "rugby", "rugby ball football"),
            ("🎱", "8ball", "billiards pool 8 ball"),
            ("🪀", "yo_yo", "yo yo toy"),
            ("🏓", "ping_pong", "ping pong table tennis"),
            ("🏸", "badminton", "badminton shuttlecock"),
            ("🥊", "boxing", "boxing glove fight"),
            ("🥋", "martial_arts", "martial arts karate judo"),
            ("🥅", "goal", "goal net soccer"),
            ("⛳", "golf", "golf flag hole"),
            ("⛸️", "skate", "ice skate skating"),
            ("🎣", "fishing", "fishing pole fish"),
            ("🤿", "diving", "diving mask scuba"),
            ("🎽", "running_shirt", "running shirt sash"),
            ("🎿", "skis", "skis skiing snow"),
            ("🛷", "sled", "sled sleigh snow"),
            ("🥌", "curling", "curling stone rock"),
            ("🎯", "dart", "dart bullseye target"),
            ("🎮", "controller", "video game controller play"),
            ("🎲", "die", "game die dice board"),
            ("♟️", "chess", "chess pawn board"),
            ("🎭", "theater", "theater mask performance"),
            ("🎨", "palette", "art palette painting"),
            ("🎪", "circus", "circus tent carnival"),
            ("🎤", "microphone", "microphone sing karaoke"),
            ("🎧", "headphones", "headphones music listen"),
            ("🎵", "music_note", "musical note song"),
            ("🎶", "music_notes", "musical notes melody"),
            ("🎼", "score", "musical score sheet"),
            ("🥁", "drum", "drum instrument music"),
            ("🎷", "saxophone", "saxophone jazz instrument"),
            ("🎸", "guitar", "guitar rock instrument"),
            ("🎺", "trumpet", "trumpet jazz instrument"),
            ("🎻", "violin", "violin instrument string"),
            ("🎳", "bowling", "bowling ball pin"),
        ],
    },
    {
        "icon": "🏠",
        "name": "Places",
        "emojis": [
            ("🌍", "earth_europe", "earth globe europe africa"),
            ("🌎", "earth_americas", "earth globe americas"),
            ("🌏", "earth_asia", "earth globe asia australia"),
            ("🗺️", "world_map", "world map travel"),
            ("🏔️", "mountain", "snow mountain peak"),
            ("🏖️", "beach", "beach umbrella sand"),
            ("🏝️", "island", "desert island tropical"),
            ("🌋", "volcano", "volcano eruption lava"),
            ("🗻", "fuji", "mount fuji japan"),
            ("🏠", "house", "house home building"),
            ("🏡", "house_garden", "house garden yard"),
            ("🏢", "office", "office building work"),
            ("🏣", "post_office", "japanese post office"),
            ("🏤", "european_post", "european post office"),
            ("🏥", "hospital", "hospital medical clinic"),
            ("🏦", "bank", "bank building money"),
            ("🏨", "hotel", "hotel accommodation"),
            ("🏩", "love_hotel", "love hotel romance"),
            ("🏪", "convenience", "convenience store 24h"),
            ("🏫", "school", "school education"),
            ("🏬", "department", "department store mall"),
            ("🏭", "factory", "factory industry"),
            ("🏯", "castle_japanese", "japanese castle"),
            ("🏰", "castle", "european castle disney"),
            ("💒", "wedding", "wedding chapel romance"),
            ("🗼", "eiffel", "eiffel tower paris"),
            ("🗽", "statue", "statue of liberty nyc"),
            ("⛪", "church", "church christian wedding"),
            ("🕌", "mosque", "mosque islam muslim"),
            ("🛕", "temple", "hindu temple"),
            ("🕍", "synagogue", "synagogue jewish"),
            ("⛩️", "shrine", "shinto shrine japan"),
            ("🎡", "ferris_wheel", "ferris wheel amusement park"),
            ("🎢", "roller_coaster", "roller coaster amusement"),
            ("🎠", "carousel", "carousel horse merry go round"),
            ("🚂", "locomotive", "locomotive train steam"),
            ("🚃", "railway_car", "railway car train"),
            ("🚄", "bullet_train", "bullet train shinkansen fast"),
            ("🚅", "bullet_front", "bullet train nose fast"),
            ("🚗", "car", "car automobile vehicle"),
            ("🚕", "taxi", "taxi cab"),
            ("🚙", "suv", "suv vehicle car"),
            ("🚌", "bus", "bus vehicle"),
            ("🚎", "trolley", "trolley bus tram"),
            ("🏎️", "race_car", "racing car formula 1"),
            ("🚓", "police_car", "police car patrol"),
            ("🚑", "ambulance", "ambulance medical emergency"),
            ("🚒", "fire_truck", "fire truck emergency"),
            ("🚜", "tractor", "tractor farm vehicle"),
            ("🛵", "scooter", "motor scooter vespa"),
            ("🚲", "bike", "bicycle bike cycle"),
            ("✈️", "airplane", "airplane flight travel"),
            ("🚀", "rocket", "rocket space launch"),
            ("🛸", "ufo", "ufo alien flying saucer"),
            ("🚁", "helicopter", "helicopter rotorcraft"),
            ("🛶", "canoe", "canoe kayak boat"),
            ("⛵", "sailboat", "sailboat yacht sail"),
            ("🚢", "ship", "ship boat cruise"),
        ],
    },
    {
        "icon": "💡",
        "name": "Objects",
        "emojis": [
            ("⌚", "watch", "watch time wrist"),
            ("📱", "phone", "smartphone mobile iphone"),
            ("💻", "laptop", "laptop computer macbook"),
            ("⌨️", "keyboard", "keyboard type"),
            ("🖥️", "desktop", "desktop computer monitor"),
            ("🖨️", "printer", "printer print document"),
            ("🖱️", "mouse", "computer mouse"),
            ("💽", "disk", "computer disk minidisc"),
            ("💾", "floppy", "floppy disk save retro"),
            ("💿", "cd", "cd optical disc"),
            ("📀", "dvd", "dvd bluray disc"),
            ("🎥", "movie_camera", "movie camera film"),
            ("📷", "camera", "camera photo picture"),
            ("📸", "camera_flash", "camera flash selfie"),
            ("📹", "video_camera", "video camera camcorder"),
            ("🎬", "clapper", "clapper board movie action"),
            ("📺", "tv", "television tv screen"),
            ("📻", "radio", "radio music tuner"),
            ("🔋", "battery", "battery power charge"),
            ("🔌", "plug", "plug power electric"),
            ("💡", "bulb", "light bulb idea"),
            ("🔦", "flashlight", "flashlight torch light"),
            ("🕯️", "candle", "candle light wax"),
            ("📖", "book", "book open read"),
            ("📕", "closed_book", "closed book red"),
            ("📗", "green_book", "green book"),
            ("📘", "blue_book", "blue book"),
            ("📙", "orange_book", "orange book"),
            ("📚", "books", "books stack library"),
            ("📓", "notebook", "notebook journal diary"),
            ("📒", "ledger", "ledger notebook"),
            ("📃", "scroll", "scroll paper document"),
            ("📜", "scroll_ancient", "scroll parchment ancient"),
            ("📄", "document", "document file page"),
            ("📰", "newspaper", "newspaper news press"),
            ("📑", "bookmarks", "bookmarks tabs"),
            ("🔖", "bookmark", "bookmark tag ribbon"),
            ("💰", "money_bag", "money bag rich wealth"),
            ("💴", "yen", "yen banknote japan"),
            ("💵", "dollar", "dollar banknote usd"),
            ("💶", "euro", "euro banknote europe"),
            ("💷", "pound", "pound banknote uk"),
            ("💸", "flying_money", "flying money loss spend"),
            ("🔧", "wrench", "wrench tool fix"),
            ("🔨", "hammer", "hammer tool build"),
            ("🪛", "screwdriver", "screwdriver tool screw"),
            ("🔩", "nut_bolt", "nut and bolt hardware"),
            ("⚙️", "gear", "gear settings cog"),
            ("🗜️", "clamp", "clamp compress tool"),
            ("💣", "bomb", "bomb explode danger"),
            ("🔫", "gun", "gun pistol water"),
            ("💊", "pill", "pill medicine medication"),
            ("💉", "syringe", "syringe needle vaccine"),
            ("🩺", "stethoscope", "stethoscope doctor medical"),
            ("🔬", "microscope", "microscope science lab"),
            ("🔭", "telescope", "telescope astronomy space"),
            ("📡", "satellite", "satellite dish antenna signal"),
            ("💎", "gem", "gem stone diamond jewel"),
        ],
    },
    {
        "icon": "💬",
        "name": "Symbols",
        "emojis": [
            ("❤️", "heart", "heart love red"),
            ("🧡", "orange_heart", "orange heart"),
            ("💛", "yellow_heart", "yellow heart"),
            ("💚", "green_heart", "green heart"),
            ("💙", "blue_heart", "blue heart"),
            ("💜", "purple_heart", "purple heart"),
            ("🖤", "black_heart", "black heart dark"),
            ("🤍", "white_heart", "white heart"),
            ("🤎", "brown_heart", "brown heart"),
            ("💔", "broken_heart", "broken heart break sad"),
            ("❣️", "heart_exclamation", "heart exclamation emphasis"),
            ("💕", "two_hearts", "two hearts love"),
            ("💞", "revolving_hearts", "revolving hearts love"),
            ("💓", "beating_heart", "beating heart pulse"),
            ("💗", "growing_heart", "growing heart love"),
            ("💖", "sparkling_heart", "sparkling heart shiny"),
            ("💝", "heart_ribbon", "heart ribbon gift love"),
            ("💘", "cupid", "cupid heart arrow love"),
            ("💟", "heart_decorative", "heart decoration"),
            ("☮️", "peace", "peace symbol"),
            ("✝️", "cross", "latin cross christian"),
            ("☪️", "star_crescent", "star and crescent islam"),
            ("🕉️", "om", "om hindu"),
            ("☸️", "wheel_dharma", "wheel of dharma buddhist"),
            ("✡️", "star_david", "star of david jewish"),
            ("🔯", "six_pointed", "six pointed star"),
            ("🪯", "khanda", "khanda sikh"),
            ("🕎", "menorah", "menorah hanukkah jewish"),
            ("🔤", "abc", "abc english alphabet"),
            ("🔠", "capital_abc", "capital abc input"),
            ("🔡", "lowercase_abc", "lowercase abc"),
            ("🔢", "1234", "input numbers 1234"),
            ("🔣", "symbols", "input symbols"),
            ("🆗", "squared_ok", "ok button squared"),
            ("🆕", "squared_new", "new button fresh"),
            ("🆙", "squared_up", "up button"),
            ("🆒", "squared_cool", "cool button trendy"),
            ("🆓", "squared_free", "free button complimentary"),
            ("🆔", "id_button", "id identification button"),
            ("🈳", "ideograph_empty", "empty japanese character"),
            ("🈹", "ideograph_discount", "discount japanese character"),
            ("🆚", "vs_button", "vs versus button"),
            ("📵", "no_phone", "no mobile phones ban"),
            ("🔞", "no_underage", "no underage 18 adult"),
            ("☢️", "radioactive", "radioactive hazard"),
            ("☣️", "biohazard", "biohazard danger virus"),
            ("⚠️", "warning", "warning caution alert"),
            ("🚸", "children", "children crossing school"),
            ("⛔", "no_entry", "no entry prohibited"),
            ("🚫", "prohibited", "prohibited ban forbidden"),
            ("🚳", "no_bikes", "no bicycles"),
            ("🚭", "no_smoking", "no smoking prohibited"),
            ("🚯", "no_litter", "no littering do not litter"),
            ("🚱", "non_potable", "non potable water"),
            ("🚷", "no_pedestrians", "no pedestrians"),
            ("📛", "name_badge", "name badge tag"),
            ("🔇", "mute_speaker", "muted speaker silent"),
            ("🔈", "low_volume", "low volume speaker"),
            ("🔉", "medium_volume", "medium volume speaker"),
            ("🔊", "high_volume", "high volume speaker loud"),
            ("📣", "megaphone", "megaphone announce shout"),
            ("📢", "loudspeaker", "loudspeaker announcement"),
            ("🔔", "bell", "bell notification ring"),
            ("🔕", "no_bell", "bell with slash silent"),
            ("♻️", "recycle", "recycle recycling green"),
            ("🛐", "place_worship", "place of worship religion"),
            ("⚕️", "medical", "medical symbol staff aesculapius"),
            ("💹", "chart_up", "chart increasing yen market"),
            ("♿", "wheelchair", "wheelchair accessibility"),
            ("🚹", "mens", "men restroom male"),
            ("🚺", "womens", "women restroom female"),
            ("🚻", "restroom", "restroom bathroom wc"),
            ("🚼", "baby", "baby changing station"),
            ("🚾", "water_closet", "water closet wc toilet"),
            ("🛂", "passport", "passport control customs"),
            ("🛃", "customs", "customs border declaration"),
            ("🛄", "baggage", "baggage claim luggage"),
            ("🛅", "left_luggage", "left luggage storage"),
            ("🆑", "cl_button", "cl clear button"),
            ("🆘", "sos_button", "sos emergency help"),
            ("🆖", "ng_button", "ng no good button"),
            ("✅", "check_mark", "check mark button yes"),
            ("❌", "cross_mark", "cross mark x no wrong"),
            ("❓", "question", "question mark help"),
            ("❗", "exclamation", "exclamation mark emphasis"),
            ("➕", "plus", "plus add math"),
            ("➖", "minus", "minus subtract math"),
            ("➗", "divide", "divide division math"),
            ("❕", "grey_exclamation", "white exclamation mark"),
            ("❔", "grey_question", "white question mark"),
            ("💤", "zzz", "zzz sleeping tired"),
            ("💢", "anger", "anger symbol mad"),
            ("💬", "speech", "speech balloon chat bubble"),
            ("🗯️", "right_anger", "right anger bubble"),
            ("💭", "thought", "thought balloon thinking"),
            ("🕳️", "hole", "hole rabbit void"),
            ("👁️‍🗨️", "speech_eye", "eye in speech bubble i spy"),
            ("🔰", "beginner", "japanese beginner shoshinsha mark"),
            ("🔱", "trident", "trident emblem symbol"),
            ("〽️", "part_alternation", "part alternation mark"),
        ],
    },
]


def search_emojis(query: str, limit: int = 10) -> list[tuple[str, str, str]]:
    query = query.lower().strip()
    if not query:
        return []
    results = []
    for cat in EMOJI_CATEGORIES:
        for emoji, name, keywords in cat["emojis"]:
            if query in name.lower() or query in keywords.lower():
                results.append((emoji, name, keywords))
                if len(results) >= limit:
                    return results
    return results
