from __future__ import annotations

import asyncio
from typing import TYPE_CHECKING, Protocol

from tgm.core.models import Channel, ChannelInfo, Message, User
from tgm.core.store import Store

if TYPE_CHECKING:
    pass


class ClientProtocol(Protocol):
    store: Store
    event_queue: asyncio.Queue  # Queue[ClientEvent]

    # Convenience accessors — implementations delegate to store.
    # Keeping these on the protocol lets existing call-sites (client.users etc.)
    # keep working without a big-bang migration.
    @property
    def users(self) -> dict[str, User]: ...
    @property
    def channels(self) -> dict[str, Channel]: ...
    @property
    def channel_list(self) -> list[Channel]: ...
    @property
    def current_user(self) -> User | None: ...
    @property
    def current_user_id(self) -> str | None: ...

    async def is_authorized(self) -> bool: ...
    async def get_me(self) -> User | None: ...
    async def reset_session(self) -> None: ...
    async def send_code(self, phone: str) -> None: ...
    async def resend_code_sms(self, phone: str) -> None: ...
    async def sign_in(self, phone: str, code: str) -> User: ...
    async def sign_in_with_password(self, password: str) -> User: ...

    async def load_dialogs(self, limit: int = 100) -> None: ...
    async def disconnect(self) -> None: ...

    async def get_channel_messages(
        self, channel_id: str, limit: int = 50
    ) -> list[Message]: ...
    async def add_message(
        self, text: str, channel_id: str, reply_to_msg_id: str | None = None
    ) -> Message: ...
    async def send_file(
        self,
        channel_id: str,
        file_path: str,
        caption: str = "",
        reply_to_msg_ud: str | None = None,
    ) -> Message: ...
    async def mark_as_read(self, channel_id: str) -> None: ...
    async def delete_message(self, channel_id: str, message_id: str) -> None: ...
    async def edit_message(
        self, channel_id: str, message_id: str, text: str
    ) -> None: ...
    async def pin_message(self, channel_id: str, message_id: str) -> None: ...
    async def unpin_message(self, channel_id: str) -> None: ...
    async def forward_message(
        self, from_channel_id: str, to_channel_id: str, message_id: str
    ) -> None: ...

    async def create_group(self, title: str) -> Channel: ...
    async def search_global(self, query: str, limit: int = 20) -> list[Channel]: ...
    async def open_channel(self, channel_id: str) -> Channel: ...
    async def get_channel_info(self, channel_id: str) -> ChannelInfo: ...
